from django.urls import path
from django.contrib.auth import views as auth_views
from . import views_web

urlpatterns = [
    # Landing page: unauthenticated visitors are asked to log in here.
    # Already-authenticated visitors are bounced straight to the Dashboard.
    path("",                          auth_views.LoginView.as_view(
                                           template_name="cdb/login.html",
                                           redirect_authenticated_user=True,
                                       ),                                   name="login"),
    path("logout/",                   auth_views.LogoutView.as_view(),     name="logout"),

    path("dashboard/",                views_web.dashboard,        name="dashboard"),
    path("components/",               views_web.component_list,   name="component-list"),
    path("components/<str:pk>/",      views_web.component_detail, name="component-detail"),
    path("components/<str:pk>/properties/<str:property_id>/delete/",
                                       views_web.component_property_delete, name="component-property-delete"),
    path("components/<str:pk>/properties/<str:property_id>/update/",
                                       views_web.component_property_update, name="component-property-update"),
    path("components/<str:pk>/instances/create/",
                                       views_web.component_instance_create, name="component-instance-create"),
    path("components/<str:pk>/transfer-owner/",
                                       views_web.component_transfer_owner, name="component-transfer-owner"),
    path("inventory/",                views_web.inventory_list,   name="inventory-list"),
    path("inventory/<str:pk>/",       views_web.inventory_detail, name="inventory-detail"),
    path("inventory/<str:pk>/properties/<str:property_id>/update/",
                                       views_web.inventory_property_update, name="inventory-property-update"),
    path("inventory/<str:pk>/qr/",    views_web.inventory_qr,     name="inventory-qr"),
    path("inventory/<str:pk>/transfer-owner/",
                                       views_web.inventory_transfer_owner, name="inventory-transfer-owner"),
    path("inventory/<str:pk>/update-location/",
                                       views_web.inventory_update_location, name="inventory-update-location"),
    path("inventory/<str:pk>/update-identifiers/",
                                       views_web.inventory_update_identifiers, name="inventory-update-identifiers"),
    path("design-templates/",         views_web.template_list,    name="template-list"),
    path("design-templates/<str:pk>/", views_web.template_detail,  name="template-detail"),
    path("design-templates/<str:pk>/elements/<str:element_id>/update/",
                                       views_web.template_element_update, name="template-element-update"),
    path("design-templates/<str:pk>/elements/<str:element_id>/delete/",
                                       views_web.template_element_delete, name="template-element-delete"),
    path("designs/",                  views_web.design_list,      name="design-list"),
    path("designs/<str:pk>/",         views_web.design_detail,    name="design-detail"),
    path("designs/<str:pk>/properties/<str:property_id>/update/",
                                       views_web.design_property_update, name="design-property-update"),
    path("designs/<str:pk>/delete/",  views_web.design_delete,    name="design-delete"),
    path("designs/<str:pk>/update-location/",
                                       views_web.design_update_location, name="design-update-location"),
    path("designs/<str:pk>/elements/<str:element_id>/assign-instance/",
                                       views_web.design_element_assign_instance, name="design-element-assign-instance"),
    path("designs/<str:pk>/elements/<str:element_id>/unassign-instance/",
                                       views_web.design_element_unassign_instance, name="design-element-unassign-instance"),
    path("systems/",                  views_web.system_list,      name="system-list"),
    path("systems/<str:pk>/",         views_web.system_detail,    name="system-detail"),
    path("institutions/",             views_web.institution_list, name="institution-list"),
    path("logs/",                     views_web.log_list,         name="log-list"),
    path("users/",                    views_web.user_list,        name="user-list"),
    path("users/<str:username>/inventory/", views_web.user_inventory,  name="user-inventory"),
    path("locations/<str:pk>/inventory/",   views_web.location_inventory, name="location-inventory"),
]
