# Generated by Django 6.0.6 on 2026-06-24 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('documentation', 'Documentation'), ('qa', 'QA'), ('lattice', 'Lattice'), ('safety', 'Safety'), ('maintenance', 'Maintenance'), ('design', 'Design'), ('status', 'Status'), ('other', 'Other')], default='other', max_length=32)),
                ('handler', models.CharField(blank=True, choices=[('', 'None'), ('pdmlink', 'PDMLink'), ('component_design', 'Component Design'), ('traveler_template', 'Traveler Template'), ('traveler_instance', 'Traveler Instance'), ('document', 'Document'), ('image', 'Image'), ('http_link', 'HTTP Link'), ('currency', 'Currency'), ('boolean', 'Boolean'), ('date', 'Date')], default='', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('default_units', models.CharField(blank=True, max_length=64)),
                ('default_value', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('url', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_writeable', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('alternate_name', models.CharField(blank=True, max_length=256)),
                ('model_number', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('project', models.CharField(blank=True, default='ePIC', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='cdb.componentfunction')),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cdb.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_writeable', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('qr_id', models.CharField(max_length=32, unique=True)),
                ('tag', models.CharField(blank=True, max_length=128)),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='cdb.component')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cdb.group')),
            ],
            options={
                'ordering': ['qr_id'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_writeable', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('project', models.CharField(blank=True, default='ePIC', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cdb.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DesignElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('child_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_elements', to='cdb.design')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_memberships', to='cdb.component')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='cdb.design')),
                ('installed_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_at', to='cdb.componentinstance')),
            ],
            options={
                'ordering': ['element_name'],
                'unique_together': {('design', 'element_name')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location_type', models.CharField(choices=[('building', 'Building'), ('room', 'Room'), ('cabinet', 'Cabinet'), ('shelf', 'Shelf'), ('other', 'Other')], default='room', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cdb.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='cdb.location'),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, choices=[('', 'General'), ('installation', 'Installation'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('repair', 'Repair'), ('decommission', 'Decommission'), ('other', 'Other')], default='', max_length=32)),
                ('entry', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='log_attachments/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='cdb.component')),
                ('component_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='cdb.componentinstance')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='cdb.design')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdb_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=128)),
                ('value', models.TextField(blank=True)),
                ('units', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_dynamic', models.BooleanField(default=False)),
                ('user_writable', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='cdb.component')),
                ('component_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='cdb.componentinstance')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='cdb.design')),
                ('design_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='cdb.designelement')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb.propertytype')),
            ],
            options={
                'ordering': ['property_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=128)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('manufacturer', 'Manufacturer'), ('both', 'Vendor & Manufacturer')], default='vendor', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb.component')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb.source')),
            ],
            options={
                'unique_together': {('component', 'source')},
            },
        ),
        migrations.AddField(
            model_name='component',
            name='sources',
            field=models.ManyToManyField(blank=True, through='cdb.ComponentSource', to='cdb.source'),
        ),
        migrations.AddField(
            model_name='componentfunction',
            name='technical_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functions', to='cdb.technicalsystem'),
        ),
        migrations.AddField(
            model_name='component',
            name='technical_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='cdb.technicalsystem'),
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('name', 'project')},
        ),
    ]
