# Generated by Django 6.0.6 on 2026-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, help_text='City (for institution-level locations)', max_length=64),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, help_text='Country (for institution-level locations)', max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('institution', 'Institution'), ('building', 'Building'), ('room', 'Room'), ('cabinet', 'Cabinet'), ('shelf', 'Shelf'), ('other', 'Other')], default='room', max_length=16),
        ),
    ]
